### ISSUE TITLE
Synchronization failed: Undefined property: stdClass::$base_amount

### ISSUE THREAD

**Issue by jorgb90** [dealer4dealer/magento2-payment-cost-example#2]
Trying to send payment fees set with the Mollie plugin, but getting this error in Xcore. It seems to be either:

Synchronization failed: Orderline sku is invalid (must be a guid) (when order has fees)

or

Synchronization failed: Undefined property: stdClass::$base_amount (when order has no fees)

What am I missing?

**Comment by jorgb90** [comment]
Ok for "Synchronization failed: Orderline sku is invalid (must be a guid)" I missed a setting in Xcore. So thats solved, but "Synchronization failed: Undefined property: stdClass::$base_amount" still stands. It shouldn't be needed when there are not payment costs right? In the plugin we use:

if ($resultOrder->getBaseMolliePaymentFee() > 0) {

**Comment by jorgb90** [comment]
Mm it is required. Removed the if statement and set it as 0. Both errors are now solved :)

**Comment by Tjab** [comment]
On M2 default items / lines and in the xCore psp cost object the base amount must be defined. It can be null, but has to be there. We take the base amount and use it as domestic currency, the normal non-base amount is used as foreign currency.

Please submit a ticket via servicedesk@xcore.nl and mention which integration (see the number in the address bar when you are viewing your integration/app) you're experiencing these problems on so we can help you out via our ticket system. 

Thanks!
